use_frameworks!

target 'ThinCloud_Example' do
  platform :ios, '11.0'

  pod 'SwiftLint'
  pod 'ThinCloud', :path => '../'

  target 'ThinCloud_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
