use_frameworks!

target 'ThinCloud_Example' do
  pod 'ThinCloud', :path => '../'

  target 'ThinCloud_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
